spring:
  jpa:
    show-sql: false
  liquibase:
    contexts: prod

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: INFO
    com.maestros: INFO

app:
  security:
    require-https: true
    cors:
      allowed-origins: "https://maestros.app"
