spring:
  profiles:
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: ${SQLSERVER_URL}
    username: ${SQLSERVER_USERNAME}
    password: ${SQLSERVER_PASSWORD}
    hikari:
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20

  data:
    mongodb:
      uri: ${MONGODB_URI}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080
  tomcat:
    connection-timeout: 5000ms
    keep-alive-timeout: 20000ms
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true

app:
  azure:
    storage-base-url: ${AZURE_STORAGE_BASE_URL:}

logging:
  level:
    root: INFO
