spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${SQLSERVER_URL}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

logging:
  level:
    root: INFO
    com.maestros: DEBUG

app:
  security:
    require-https: false
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:4200"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
